import java.util.ArrayList;
public class LivreDeRecette {
    //Cette classe utilise le pattern singleton et est notre livre de recette.
    //Ellle contient un tableau de recette
    private static final Recette r01 = new Recette("Pâtes carbonara", new Ingredient[] {Placard.placard[0],Placard.placard[13],Placard.placard[23],Placard.placard[18],Placard.placard[15]}, "1.Cuire les pâtes dans un grand volume d'eau bouillante salée.\n 2.Emincer les oignons et les faire revenir à la poêle. Ajouter les lardons en fin de cuisson.\n 3.Préparer dans un saladier les oeufs, le sel, le poivre et mélanger.\n 4.Retirer les lardons du feu dès qu'ils sont dorés et les ajouter au mélange\n 5.Une fois les pâtes cuite les égoutter.\n 6.Et incorporer le mélange.\n 7.Bien mélanger et ajouter herbes et épices de votre choix.\n 8.Remettre sur le feu pour réchauffer le tout.\n 9.Servir, vous pouvez également agrémenter votre plat avec des champignons.\n");
    private static final Recette r02 = new Recette("Omelette", new Ingredient[] {Placard.placard[0],Placard.placard[5],Placard.placard[7],Placard.placard[25]},"1.Laver les légumes, éplucher les légumes.\n2.Couper les courgettes et les carottes en fines lamelles.\n3.Dans une poêle, mettre 3 cuillères à soupe d'huile d'olive.\n4.Faire sauter les légumes pendant 15 à 20 min max le temps qu'ils soit dorés.\n5.Veillez à mettre carottes et pomme de terre avant, car ces derniers cuisent moins vite.\n6.Ajouter sel, poivre et paprika.\n7.Couper les échalotes en fines lamelles et les ajouter aux légumes.\n8.Dans un bol, battre les œufs.\n9.Ajoutez oeufs, une petite pincée de sel et une mini cuillère à café d'huile d'olive. Verser sur les légumes.\n");
    private static final Recette r03 = new Recette("Tarte aux pommes", new Ingredient[] {Placard.placard[9],Placard.placard[21],Placard.placard[8],Placard.placard[4]}, "1.Éplucher et découper en morceaux 4 Golden.\n2.Faire une compote : les mettre dans une casserole avec un peu d'eau.Bien remuer. Quand les pommes commencent à ramollir, ajouter un sachet de sucre vanillé.\n3.Vous saurez si la compote est prête une fois que les pommes ne seront plus dures du tout. Ce n'est pas grave s'il reste quelques morceaux.\n4.Pendant que la compote cuit, éplucher et couper en quatre les deux dernières pommes, puis, couper les quartiers en fines lamelles;\n5.Préchauffer le four à 210°C (thermostat 7).\n6.Laisser un peu refroidir la compote et étaler la pâte dans un moule et la piquer avec une fourchette.\n7.Verser la compote sur la pâte et placer les lamelles de pommes en formant une spirale ou plusieurs cercles, au choix ! Disposer des lamelles de beurre dessus.\n8.Mettre au four et laisser cuire pendant 30 min max.9.Surveiller la cuisson. Vous pouvez ajouter un peu de sucre vanillé sur la tarte.");
    private static final Recette r04 = new Recette("Soupe de légumes", new Ingredient[] {Placard.placard[23],Placard.placard[19],Placard.placard[5],Placard.placard[6],Placard.placard[7]}, "1.Coupez les tomates en petits dés.\n2.Mettez les dés de tomates dans un bol et salez.\n3.Ajoutez l'huile d'olive.\n4.Coupez l'ail en petits morceaux.\n5.Ajoutez les épices de votre choix.\n6.Coupez les carottes en tranches et ajoutez-les aux tomates.\n7.Coupez les boules de fromage en tranches puis en dés, laissez dégorger sur une assiette.\n8.Ajoutez le pesto dans le bol avec les tomates et mélangez.\n9.Versez les pâtes dans un grand volume d'eau bouillante salée. Quand les pâtes sont cuites, égouttez-les, mélangez tomate et fromage.\n");
    private static final Recette r05 = new Recette("Salade de pâtes", new Ingredient[] {Placard.placard[13],Placard.placard[19],Placard.placard[22],Placard.placard[7],Placard.placard[12]}, "1.Coupez les tomates en petits dés.\n2.Mettez les dés de tomates dans un bol et salez.\n3.Ajoutez l'huile d'olive.\n4.Coupez l'ail en petits morceaux.\n5.Ajoutez les épices de votre choix.\n6.Coupez les carottes en tranches et ajoutez-les aux tomates.\n7.Coupez les boules de fromage en tranches puis en dés, laissez dégorger sur une assiette.\n8.Ajoutez le pesto dans le bol avec les tomates et mélangez.\n9.Versez les pâtes dans un grand volume d'eau bouillante salée. Quand les pâtes sont cuites, égouttez-les, mélangez tomate et fromage.\n");
    private static final Recette r06 = new Recette("Ratatouille", new Ingredient[] {Placard.placard[19],Placard.placard[5],Placard.placard[6],Placard.placard[23],Placard.placard[24]}, "1.Coupez les tomates pelées en quartiers,les aubergines et les courgettes en rondelles.\n2.Emincez les poivrons en lamelles et l'oignon en rouelles.\n3.Chauffez 2 cuillères à soupe d'huile dans une poêle.\n4.Faites-y fondre les oignons et les poivrons.\n5.Lorsqu'ils sont tendres, ajoutez les tomates, l'ail haché, le thym et le laurier.\n6.Salez, poivrez et laissez mijoter doucement à couvert durant 45 minutes.\n7.Pendant ce temps, préparez les aubergines et les courgettes. Faites les cuire séparemment ou non dans l'huile d'olive pendant 15 minutes.\n8.Vérifiez la cuisson des légumes pour qu'ils ne soient plus fermes. Ajoutez les alors au mélange de tomates.\n");
    private static final Recette r07 = new Recette("Cookies", new Ingredient[] {Placard.placard[17],Placard.placard[4],Placard.placard[0],Placard.placard[21],Placard.placard[1],Placard.placard[16]}, "1.Détailler le chocolat en pépites.\n2.Préchauffer le four à 180°C (thermostat 6). Dans un saladier, mettre 75 g de beurre, le sucre, l'oeuf entier, la vanille et mélanger le tout.\n3.Ajouter petit à petit la farine mélangée à la levure.\n4.Ajouter les pépites de chocolat.\n5.Avec une feuille de papier essuie-tout, beurrer une plaque allant au four et former les cookies sur la plaque.\n6.Pour former les cookies, utiliser 2 cuillères à soupe et faire des petits tas espacés les uns des autres; ils grandiront à la cuisson.\n8.Enfourner pour 10 minutes de cuisson.\n9.Laissez refroidir 10 minutes et dégustez.\n");
    private static final Recette r08 = new Recette("Quiche lorraine", new Ingredient[] {Placard.placard[9],Placard.placard[4],Placard.placard[18],Placard.placard[0],Placard.placard[2]}, "1.Préchauffer le four à 180°C (thermostat 6).\n2.Etaler la pâte dans un moule, la piquer à la fourchette. Parsemer de copeaux de beurre.\n3.Faire rissoler les lardons à la poêle puis les éponger avec une feuille d essuie-tout.\n4.Battre les oeufs, avec un peu de lait.\n5.Ajouter les lardons.\n6.Assaisonner de sel, de poivre et de muscade.\n7.Verser sur la pâte.\n8.Cuire 45 à 50 min.\n9.Cest prêt.\n");
    private static final Recette r09 = new Recette("Lasagnes", new Ingredient[] {Placard.placard[22],Placard.placard[23],Placard.placard[7],Placard.placard[20],Placard.placard[19],Placard.placard[4],Placard.placard[2],Placard.placard[13]}, "1.Faire revenir gousses hachées d'ail et les oignons émincés dans un peu d'huile d'olive.\n2.Ajouter la carotte et la viande et faire revenir le tout.\n3.Au bout de quelques minutes, ajouter du vin rouge. Laisser cuire jusqu'à évaporation.\n4.Ajouter la purée de tomates, l'eau et les herbes. Saler, poivrer, puis laisser mijoter à feu doux 45 minutes.\n5.Préparer la béchamel : faire fondre le beurre.\n6.Hors du feu, ajouter la farine d'un coup. Remettre sur le feu et remuer avec un fouet jusqu'à l'obtention d'un mélange bien lisse.\n7.Ajouter le lait peu à peu. Remuer sans cesse, jusqu'à ce que le mélange s'épaississe.\n8.Ensuite, parfumer avec la muscade, saler, poivrer. Laisser cuire environ 5 minutes, en remuant. Préchauffer le four à 200°C Huiler le plat à lasagnes.\n9.Poser une fine couche de béchamel puis des feuilles de lasagnes, de la bolognaise, de la béchamel et du parmesan. Répéter, Enfourner pour 25 minutes.\n");
    private static final Recette r10 = new Recette("Sushis", new Ingredient[] {Placard.placard[3],Placard.placard[21],Placard.placard[11] }, "1.Lavez le riz plusieurs fois, jusqu'à ce que le qui s'en écoule soit bien claire (afin d'en ôter le maximum d'amidon).\n2.Mettez-le dans une casserole, ajoutez l’eau, couvrez et portez à ébullition.\n3.Laissez cuire à couvert pendant 15 minutes puis retirez du feu et laissez en attente à couvert pendant 10 minutes.\n4.Dans un bol, mélangez le vinaigre de riz, le sucre, et le sel. Remuez jusqu'à ce que le sucre soit entièrement dissout.\n5.Versez cette préparation sur le riz et mélangez.\n6.Laissez refroidir à température ambiante.\n7.Pendant ce temps, taillez le filet de saumon en fines lamelles.\n8.Humidifiez vos mains et formez des petits pâtés de riz de forme ovale, de la longueur des lamelles de poisson.\n9.Posez une lamelle de saumon sur chaque boulette de riz.\n");
    private static final Recette r11 = new Recette("Pizza", new Ingredient[] {Placard.placard[24],Placard.placard[8],Placard.placard[19],Placard.placard[12],Placard.placard[18]}, "1.Rincez les poivrons.\n2.Épépinez-les et coupez-les en lanières.\n3.Faites-les revenir dans une poêle avec un peu d'huile d'olive.\n5.Faire cuir 10 minutes à feu moyen.\n6.Réservez sur le côté.\n7.Déroulez la pâte à pizza sur la plaque du four recouverte de papier cuisson.\n8.Étalez-y du coulis de tomate, ajoutez les poivrons, le chorizo et le Cambozola coupé en tranches.\n9.Faites cuire +/- 15 minutes à 200°C.\n");
    private static final Recette r12 = new Recette("Frites", new Ingredient[] {Placard.placard[25]},"1.Peler les pommes de terre et retirer les yeux.\n2.Les découper en bâtonnets d’environ 1 cm de diamètre.\n3.Les passer très rapidement sous l’eau puis les sécher parfaitement dans un torchon. Elles ne doivent pas présenter de traces d’humidité.\n4.Le secret de la cuisson des frites réside dans le fait de réaliser 2 cuissons successives à des températures différentes\n5.Faites cuire 5 minutes à 140-150° pour les précuire puis 2-3 minutes à 180° pour les dorer.\n6.bien séparer les 2 bains de friture en laissant le temps aux frites de « sécher » entre les 2 bains.\n7.Sortir le panier du bain de friture et secouer le panier pour bien égoutter l’huile.\n8.Une fois le 2ème bain réalisé, bien secouer le panier puis égoutter sur un papier absorbant.\n9.Saler tout de suite au sel fin puis juste avant de servir un peu de fleur de sel ou de gros sel.\n");
    private static final Recette r13 = new Recette("Club Sandwich", new Ingredient[] {Placard.placard[0],Placard.placard[19],Placard.placard[10]},"1.Faites des tranches avec les tomates et les oeufs durs.\n2.Taillez les blancs de poulet en lamelles. Salez, poivrez et parsemez de paprika.\n3.Détaillez les feuilles de laitues.\n4.Faites rissolez le bacon à sec. Grillez le pain.\n5.Tartinez une tranche de mayonnaise. Déposez la laitue, les tomates, les blancs de poulet, l'emmental, les œufs et le bacon.\n6.Couvrez d'une tranche de pain tartinée de mayonnaise puis, refaites un étage de garniture. Terminez par la laitue.\n7.Couvrez d'une tranche de pain tartinée de mayonnaise.\n8.Faites 3 autres sandwiches de la même manière. Découpez-les en triangle et dégustez avec des frites.\n9.Dégustez!\n");
    private static final Recette r14 = new Recette("Escalope haricots", new Ingredient[] {Placard.placard[14],Placard.placard[10],Placard.placard[0],Placard.placard[1],Placard.placard[4]},"1.Epluchez la carotte, découpez en petits cubes ainsi que les oignons\n2.Découpez les saucisses en petits cubes également (vous pouvez les remplacer par des dés de poulet, des petites crevettes etc.)\n3.Faites-les revenir dans une poêle anti-adhésive avec l'huile quelques minutes\n4.Ajoutez alors les carottes, laissez dorer 5 minutes en ajoutant la sauce soja.\n5.Ajoutez le riz déjà cuit, mélangez bien pour décoller les grains de riz.\n6.Ajoutez l'oignon (ou ciboule), le sel, et mélangez.\n7.Versez alors les oeufs battus sur le riz directement et mélangez pour que l'oeuf se répartisse bien sur tout le riz.\n8.Mélangez bien pour décoller les grains de riz à nouveau.\n9.Ajoutez enfin le maïs et les petits pois, poivrez et poursuivez la cuisson 2 minutes, c'est prêt !\n");
    private static final Recette r15 = new Recette("Riz cantonnais", new Ingredient[] {Placard.placard[7],Placard.placard[23],Placard.placard[18],Placard.placard[3]},"1.Epluchez la carotte, découpez en petits cubes ainsi que les oignons\n2.Découpez les saucisses en petits cubes également (vous pouvez les remplacer par des dés de poulet, des petites crevettes etc.)\n3.Faites-les revenir dans une poêle anti-adhésive avec l'huile quelques minutes\n4.Ajoutez alors les carottes, laissez dorer 5 minutes en ajoutant la sauce soja.\n5.Ajoutez le riz déjà cuit, mélangez bien pour décoller les grains de riz.\n6.Ajoutez l'oignon (ou ciboule), le sel, et mélangez.\n7.Versez alors les oeufs battus sur le riz directement et mélangez pour que l'oeuf se répartisse bien sur tout le riz.\n8.Mélangez bien pour décoller les grains de riz à nouveau.\n9.Ajoutez enfin le maïs et les petits pois, poivrez et poursuivez la cuisson 2 minutes, c'est prêt !\n");
    private static final Recette r16 = new Recette("Flan", new Ingredient[] {Placard.placard[0],Placard.placard[2],Placard.placard[21]},"1.Préchauffez le four th.6 (180°C).\n2.Dans une casserole, faites bouillir le lait.\n3.Battez les oeufs avec le sucre et le sucre vanillé.\n4.Puis versez le lait bouillant sur le mélange, tout en remuant au fouet.\n5.Versez du caramel dans votre moule à flan (un moule à manqué par exemple) ou dans des ramequins individuels.\n6.Versez ensuite votre préparation.\n7.Enfournez au bain-marie pendant 25 min.\n8.Après le temps de cuisson, laissez refroidir 15 min.\n9.pour le(s) démouler, mettez-le(s) à l'envers sur un plat.\n");
    private static final Recette r17 = new Recette("Gratin courgettes", new Ingredient[] {Placard.placard[5],Placard.placard[0],Placard.placard[2],Placard.placard[12]},"1.Lavez les courgettes, les essuyer et les éplucher en laissant des petites bandes de peau, c'est plus esthétique et les couper en rondelles.\n2.Faire bouillir de l'eau salée dans une casserole, lorsque l'eau bout, plongez les courgettes pendant 15 minutes.\n3.Allumez le four à th.6 (200°C).\n4.Égouttez-les courgettes avant de les enfourner.\n5.Dans un saladier, mélangez l'œuf, la crème fraîche ou le lait et une bonne pincée de sel et de poivre selon vos goûts.\n6.Ajouter le gruyère râpé sur les courgettes et mélangez le tout.\n7.Versez la préparation dans un moule à gratin beurré.\n8.Ajoutez du gruyère par-dessus et mettez au four pendant 45 min.\n9.Servez votre gratin de courgettes simple et savoureux sans plus attendre. Miam !\n");
    private static final Recette r18 = new Recette("Poulet au curry", new Ingredient[] {Placard.placard[10],Placard.placard[3],Placard.placard[22],Placard.placard[23]},"1.Dans un wok, faites chauffer 1 c à s d'huile.\n2.Faites-y dorer les lamelles de poulet (procédez en plusieurs fois). Réservez.\n3.Remettez 1 c à s d'huile dans le wok.\n4.Faites suer les oignons émincés. Ajoutez l'ail et le curry, faites revenir 2 min à feu vif.\n5.Ajoutez le poulet doré.\n6.Ajoutez les dés de tomates, le sucre, mouillez avec le bouillon.\n7.Couvrez et laissez cuire à feu doux 25 min.\n8. 5 min avant la fin de cuisson, ajoutez la crème de coco. Laissez à découvert cuire 5 min sans faire bouillir.\n9.Rectifiez l'assaisonnement si nécessaire. Ajoutez le riz blanc.\n");
    private static final Recette r19 = new Recette("ile flottante", new Ingredient[] { Placard.placard[2],Placard.placard[0],Placard.placard[21] },"1.Pour la crème anglaise, faites bouillir le lait dans une casserole. Coupez la gousse de vanille en 2, grattez les grains et ajoutez-les au lait avec les morceaux de gousse.\n2.Laissez infuser et tiédir.\n3.Séparez les blancs des jaunes d’œufs. Conservez les blancs pour la suite de la recette. Dans un saladier, mélangez au batteur les jaunes avec le sucre en poudre.\n4.Versez peu à peu le lait tiédi sur les jaunes d’œufs battus. Fouettez vigoureusement et reversez le tout dans la casserole.\n5.Faites chauffer doucement pour épaissir pendant 10 min à petit feu. Le mélange ne doit pas bouillir.\n6.Veillez à bien remuer régulièrement la crème anglaise à l’aide d’une spatule en bois\n7.Lorsqu’elle nappe bien la cuillère, ôtez du feu et laissez refroidir dans un saladier. Puis réservez au réfrigérateur.\n8.Battez les blancs en neige à l’aide d’un fouet, Lorsqu’ils commencent à devenir fermes, incorporez le sucre en poudre dans une casserole, faites bouillir de l’eau.\n9.À l’aide d’une écumoire, découpez des portions de blanc d’œufs que vous plongerez dans l’eau pendant 1min. Lorsque les œufs en neige sont cuits, puis disposez-les.\n");
    private static final Recette r20 = new Recette("Chips de légumes", new Ingredient[] { Placard.placard[7],Placard.placard[5],Placard.placard[25],Placard.placard[15]},"1.Épluchez les légumes.\n2.Puis détaillez-les en fines rondelles à l’aide d’une mandoline.\n3.Rincez-les dans un saladier rempli d’eau fraîche.\n4.Puis égouttez les et épongez-les.\n5.Préchauffez le four à 150°C (th.5/6).\n6.Déposez les rondelles de légumes sur une plaque à pâtisserie anti-adhésive.Sans les chevaucher (au besoin, utilisez 2 plaques).\n7.Salez, poivrez.\n8.Enfournez et laissez cuire 25 min environ environ.\n9.Jusqu’à ce que les chips soient dorées.\n");
    
    public static final Recette[] livreDeRecette = {r01, r02,r03,r04,r05,r06,r07,r08,r09,r10,r11,r12,r13,r14,r15,r16,r17,r18,r19,r20}; //déclaration du tableau de recette
    
    private static LivreDeRecette instance = new LivreDeRecette();
    

    private LivreDeRecette(){}

    public String toString(){ //La methode toString() permettre d'afficher tout le livre de recette
        String res="je suis un livre de recette, mes recettes sont:\n ";
        for(int i=0;i<livreDeRecette.length;i++){
            res+=i+") "+livreDeRecette[i].getnomplat()+"\n";
            res+=livreDeRecette[i].getInstructions();
            res+="\n";
        }
        return res+".";
    }

    public static LivreDeRecette getLivreDeRecette(){
        return instance;
    }

    public static ArrayList<Recette> recetteSelonIngredient(int ingredienSaisie,boolean estVegetarien){
        ArrayList<Recette> recettes = new ArrayList<Recette>();
        
        for(int i = 0; i< livreDeRecette.length; i++){
            Ingredient[] ingredientsRecette = livreDeRecette[i].getIngredientsRecette();
            for(int j = 0 ; j < ingredientsRecette.length; j++){
                if(ingredientsRecette[j]==Placard.placard[ingredienSaisie-1]){
                        recettes.add(livreDeRecette[i]);
                }
            }
        }
        for(int i = 0; i< livreDeRecette.length; i++){
            Ingredient[] ingredientsRecette = livreDeRecette[i].getIngredientsRecette();
            for(int j = 0 ; j < ingredientsRecette.length; j++){
                if(estVegetarien && !(ingredientsRecette[j].vegetarien()) ){
                    recettes.remove(livreDeRecette[i]);
                }
            }
        }
        return recettes;
    }
    public static Recette recetteRandom(){
        return livreDeRecette[(int)(Math.random()*20)];
    }
}
